install.packages("DBI")
install.packages("odbc")
install.packages("RMariaDB")
connection <- dbConnect(RMariaDB::MariaDB(),
                        dsn="RMaria-connection",
                        Server = "localhost",
                        dbname = "sample_db",
                        user = "root"
)

dbListTables(connection)

dbListFields(connection,"posts")                          


queries <- c("INSERT INTO posts (id, author_id, title, description, content, date) VALUES (10,
                                                                                    r  'Zhizhang Yuan, Daoze Zhang, Junru Chen, Geifei Gu, Yang Yang',
                                                                                      'Brant-2: Foundation Model for Brain Signals',
                                                                                      'Neurons and Cognition (q-bio.NC)',
                                                                                      'Foundational models benefit from pre-training on large amounts of unlabeled data and enable strong performance in a wide variety of applications with a small amount of labeled data. Such models can be particularly effective in analyzing brain signals, as this field encompasses numerous application scenarios, and it is costly to perform large-scale annotation. In this work, we present the largest foundation model in brain signals, Brant-2. Compared to Brant, a foundation model designed for intracranial neural signals, Brant-2 not only exhibits robustness towards data variations and modeling scales but also can be applied to a broader range of brain neural data. By experimenting on an extensive range of tasks, we demonstrate that Brant-2 is adaptive to various application scenarios in brain signals. Further analyses reveal the scalability of the Brant-2, validate each components effectiveness, and showcase our models ability to maintain performance in scenarios with scarce labels. The source code and pre-trained weights are available at:',

                                                                                    '2024-2-15 16:04:11')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES (11,
                                                                                      'Rameen Atique, Hafiza Arshi Saeed, Bushra Anwar, Tehreem Rana, Ayesha Haidar, Ayesha Muazzam, Areesha Naveed, Javeria Sharif, Aqsa Perveen, Hafiza Rida Fatima, Abdul Samad',
                                                                                      'Brief overview on Bacteriophage therapy; Alternative to Antibiotics',
                                                                                      'Other Quantitative Biology (q-bio.OT)','The term bacteriophage means killer or eater of bacteria. They were initially discovered by F.W. Twort and later on, Felix dHerelle unveiled them to the world in 1910. Phage therapy has arisen as a favorable option to conventional antibiotics by reducing the multinational problem of increasing antibacterial resistance. These virulent viruses particularly prey on and contaminate bacterial strains and aid in fighting bacterial diseases. Researchers are performing various clinical trials on the bacteriophage to tackle pathogenic bacterial infections, varying from typical illnesses to highly invulnerable biofilms that cannot be treated with antibiotics. The primary experiments demonstrated that phage therapy has fewer consequences than traditional antimicrobial drugs. It is safer to use and show results within a few days. Although phage therapy has a wide range of promising results, but it also encounters diverse obstacles. One is that they are host-specific and can merely be used for personalized therapy. As thousands of bacteria can cause disease, clinicians have to construct a library of phage viruses. For successful treatment, an analysis of versatility, stability, and immune interference related to bacteriophage is necessary. Phage therapy is an excellent substitute for antibiotics as it illustrates a living base for the treatment of infections and it is climate-friendly. It only targets the pathogenic cells and has less influence on the normal microbiota. Regardless of the challenges and problems, phage therapy is approved as a beneficial approach to combating contagious infections., and it is costly to perform large-scale annotation. In this work, we present the largest foundation model in brain signals, Brant-2. Compared to Brant, a foundation model designed for intracranial neural signals, Brant-2 not only exhibits robustness towards data variations and modeling scales but also can be applied to a broader range of brain neural data. By experimenting on an extensive range of tasks, we demonstrate that Brant-2 is adaptive to various application scenarios in brain signals. Further analyses reveal the scalability of the Brant-2, validate each components effectiveness, and showcase our models ability to maintain performance in scenarios with scarce labels. The source code and pre-trained weights are available at: ',
                                                                                      '2024-2-15 07:05:33')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES (12,
                                                                                      'Kilian Pioch, Thomas Kriecherbauer, Michael Margaliot, Lars Grüne',
                                                                                      'Statistical Mechanics (cond-mat.stat-mech)',
                                                                                      'Other Quantitative Biology (q-bio.OT)',
                                                                                      'The term bacteriophage means killer or eater of bacteria. They were initially discovered by F.W. Twort and later on, Felix dHerelle unveiled them to the world in 1910. Phage therapy has arisen as a favorable option to conventional antibiotics by reducing the multinational problem of increasing antibacterial resistance. These virulent viruses particularly prey on and contaminate bacterial strains and aid in fighting bacterial diseases. Researchers are performing various clinical trials on the bacteriophage to tackle pathogenic bacterial infections, varying from typical illnesses to highly invulnerable biofilms that cannot be treated with antibiotics. The primary experiments demonstrated that phage therapy has fewer consequences than traditional antimicrobial drugs. It is safer to use and show results within a few days. Although phage therapy has a wide range of promising results, but it also encounters diverse obstacles. One is that they are host-specific and can merely be used for personalized therapy. As thousands of bacteria can cause disease, clinicians have to construct a library of phage viruses. For successful treatment, an analysis of versatility, stability, and immune interference related to bacteriophage is necessary. Phage therapy is an excellent substitute for antibiotics as it illustrates a living base for the treatment of infections and it is climate-friendly. It only targets the pathogenic cells and has less influence on the normal microbiota. Regardless of the challenges and problems, phage therapy is approved as a beneficial approach to combating contagious infections.',
                                                                                      '2024-2-12 14:34:43')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('13',
                                                                                      'Sergey V. Stasenko, Alexey N. Mikhaylov, Alexander A. Fedotov, Vladimir A. Smirnov, Victor B. Kazantsev',
                                                                                      'Astrocyte control bursting mode of spiking neuron network with memristor-implemented plasticity',
                                                                                      'Neurons and Cognition (q-bio.NC)',
                                                                                      'A mathematical model of a spiking neuron network accompanied by astrocytes is considered. The network is composed of excitatory and inhibitory neurons with synaptic connections supplied by a memristor-based model of plasticity. Another mechanism for changing the synaptic connections involves astrocytic regulations using the concept of tripartite synapses. In the absence of memristor-based plasticity, the connections between these neurons drive the network dynamics into a burst mode, as observed in many experimental neurobiological studies when investigating living networks in neuronal cultures. The memristive plasticity implementing synaptic plasticity in inhibitory synapses results in a shift in network dynamics towards an asynchronous mode. Next,it is found that accounting for astrocytic regulation in glutamatergic excitatory synapses enable the restoration of normal burst dynamics. The conditions and parameters of such astrocytic regulations impact on burst dynamics established.',
                                                                                      '2024-11-30 16:48:19')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('14',
                                                                                      'Jonathan Huml, Abiy Tasissa, Demba Ba',
                                                                                      'Clustering Inductive Biases with Unrolled Networks',
                                                                                      'Neurons and Cognition (q-bio.NC)',
                                                                                      'The classical sparse coding (SC) model represents visual stimuli as a linear combination of a handful of learned basis functions that are Gabor-like when trained on natural image data. However, the Gabor-like filters learned by classical sparse coding far overpredict well-tuned simple cell receptive field profiles observed empirically. While neurons fire sparsely, neuronal populations are also organized in physical space by their sensitivity to certain features. In V1, this organization is a smooth progression of orientations along the cortical sheet. A number of subsequent models have either discarded the sparse dictionary learning framework entirely or whose updates have yet to take advantage of the surge in unrolled, neural dictionary learning architectures. A key missing theme of these updates is a stronger notion of emph{structured sparsity}. We propose an autoencoder architecture (WLSC) whose latent representations are implicitly, locally organized for spectral clustering through a Laplacian quadratic form of a bipartite graph, which generates a diverse set of artificial receptive fields that match primate data in V1 as faithfully as recent contrastive frameworks like Local Low Dimensionality, or LLD citep{lld} that discard sparse dictionary learning. By unifying sparse and smooth coding in models of the early visual cortex through our autoencoder, we also show that our regularization can be interpreted as early-stage specialization of receptive fields to certain classes of stimuli; that is, we induce a weak clustering bias for later stages of cortex where functional and spatial segregation (i.e. topography) are known to occur. The results show an imperative for emph{spatial regularization} of both the receptive fields and firing rates to begin to describe feature disentanglement in V1 and beyond.',
                                                                                      '2023-11-30 02:02:30')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('15',
                                                                                      'Caroline Gora (PRC), Ana Dudas (PRC), Lucas Court (PRC), Anil Annamneedi (PRC), Gaëlle Lefort (PRC), Thiago-Seike Picoreti-Nakahara (PRC), Nicolas Azzopardi (PRC), Adrien Acquistapace (PRC), Anne-Lyse Lainé (PRC, PRC), Anne-Charlotte Trouillet (PRC), Lucile Drobecq (PRC), Emmanuel Pecnard (PRC), Benoit Piegu (PRC, PRC), Pascale Crépieux (PRC, PRC), Pablo Chamero (PRC), Lucie P. Pellissier (PRC)',
                                                                                      'Effect of the social environment on olfaction and social skills in WT and mouse model of autism',
                                                                                      'Neurons and Cognition (q-bio.NC)',
                                                                                      'Autism spectrum disorders are complex, polygenic and heterogenous neurodevelopmental conditions, imposing a substantial economic burden. Genetics are influenced by the environment, specifically the social experience during the critical neurodevelopmental period. Despite efficacy of early behavior interventions targeted specific behaviors in some autistic children, there is no sustainable treatment for the two core symptoms: deficits in social interaction and communication, and stereotyped or restrained behaviors or interests. In this study, we investigated the impact of the social environment on both wild-type (WT) and Shank3 knockout (KO) mice, a mouse model that reproduces core autism-like symptoms. Our findings revealed that WT mice raised in an enriched social environment maintained social interest towards new conspecifics across multiple trials. Additionally, we observed that 2 hours or chronic social isolation induced social deficits or enhanced social interaction and olfactory neuron responses in WT animals, respectively. Notably, chronic social isolation restored both social novelty and olfactory deficits, and normalized self-grooming behavior in Shank3 KO mice. These results novel insights for the implementation of behavioral intervention and inclusive classrooms programs for children with ASD.',
                                                                                      '2023-11-29 16:46:15')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('16',
                                                                                      'Sebastian Milster, Fabian Koch, Christoph Widder, Tanja Schilling, Joachim Dzubiella',
                                                                                      'Tracer dynamics in polymer networks: generalized Langevin description',
                                                                                      'Soft Condensed Matter (cond-mat.soft)Neurons and Cognition (q-bio.NC)',
                                                                                      'Tracer diffusion in polymer networks and hydrogels is relevant in biology and technology, while it also constitutes an interesting model process for the dynamics of molecules in fluctuating, heterogeneous soft matter. Here, we study systematically the time-dependent dynamics and (non-Markovian) memory effects of tracers in polymer networks based on (Markovian) implicit-solvent Langevin simulations. In particular, we consider spherical tracer solutes at high dilution in regular, tetrafunctional bead-spring polymer networks, and control the tracer-network Lennard-Jones (LJ) interactions and the polymer density. Based on the analysis of the memory (friction) kernels, we recover the expected long-time transport coefficients, and demonstrate how the short-time tracer dynamics, polymer fluctuations, and the viscoelastic response are interlinked. Further, we fit the characteristic memory modes of the tracers with damped harmonic oscillations and identify LJ contributions, bond vibrations, and slow network relaxations, which enter the kernel with an almost linear scaling with the LJ attractions. This procedure proposes a reduced functional form for the tracer memory, allowing for a convenient inter- and extrapolation of the memory kernels. This leads eventually to highly efficient simulations utilizing the generalized Langevin equation (GLE), in which the polymer network acts as an additional thermal bath with tuneable intensity.',
                                                                                      '2024-2-15 17:51:47')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('17',
                                                                                      'Justen R Geddes, Amanda Randles',
                                                                                      'Optimizing Temporal Waveform Analysis: A Novel Pipeline for Efficient Characterization of Left Coronary Artery Velocity Profiles',
                                                                                      'Quantitative Methods (q-bio.QM)',
                                                                                      'Continuously measured arterial blood velocity can provide insight into physiological parameters and potential disease states. The efficient and effective description of the temporal profiles of arterial velocity is crucial for both clinical practice and research. We propose a pipeline to identify the minimum number of points of interest to adequately describe a velocity profile of the left coronary artery. This pipeline employs a novel operation that stretches a baseline waveform to quantify the utility of a point in fitting other waveforms. Our study introduces a comprehensive pipeline specifically designed to identify the minimal yet crucial number of points needed to accurately represent the velocity profile of the left coronary artery. Additionally, the only location-dependent portion of this pipeline is the first step, choosing all of the possible points of interest. Hence, this work is broadly applicable to other waveforms. This versatility paves the way for a novel non-frequency domain method that can enhance the analysis of physiological waveforms. Such advancements have potential implications in both research and clinical treatment of various diseases, underscoring the broader applicability and impact.',
                                                                                      '2024-2-15 17:50:18')",
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('18',
                                                                                      'Generating Visual Stimuli from EEG Recordings using Transformer-encoder based EEG encoder and GAN',
                                                                                      'Rahul Mishra, Arnav Bhavsar',
                                                                                      'Artificial Intelligence (cs.AI)',
                                                                                      'In this study, we tackle a modern research challenge within the field of perceptual brain decoding, which revolves around synthesizing images from EEG signals using an adversarial deep learning framework. The specific objective is to recreate images belonging to various object categories by leveraging EEG recordings obtained while subjects view those images. To achieve this, we employ a Transformer-encoder based EEG encoder to produce EEG encodings, which serve as inputs to the generator component of the GAN network. Alongside the adversarial loss, we also incorporate perceptual loss to enhance the quality of the generated images.',
                                                                                      '2024-2-15 17:10:27')",
             
             "INSERT INTO posts (id, author_id, title, description, content, date) VALUES ('19',
                                                                                      'Ayelet C. Portnoy, Alejandro Cohen',
                                                                                      'Multi-Stage Algorithm for Group Testing with Prior Statistics',
                                                                                      'Information Theory (cs.IT)',
                                                                                      'In this paper, we propose an efficient multi-stage algorithm for non-adaptive Group Testing (GT) with general correlated prior statistics. The proposed solution can be applied to any correlated statistical prior represented in trellis, e.g., finite state machines and Markov processes. We introduce a variation of List Viterbi Algorithm (LVA) to enable accurate recovery using much fewer tests than objectives, which efficiently gains from the correlated prior statistics structure. Our numerical results demonstrate that the proposed Multi-Stage GT (MSGT) algorithm can obtain the optimal Maximum A Posteriori (MAP) performance with feasible complexity in practical regimes, such as with COVID-19 and sparse signal recovery applications, and reduce in the scenarios tested the number of pooled tests by at least $25 compared to existing classical low complexity GT algorithms. Moreover, we analytically characterize the complexity of the proposed MSGT algorithm that guarantees its efficiency.',
                                                                                      '2023-2-15 15:31:56')"
)

for (query in queries) {
  
  query_result <- dbSendQuery(connection, query)
  dbClearResult(query_result)
}


# Execute the query
query_result <- dbSendQuery(connection, query)

# clear the result after executing the query
dbClearResult(query_result)


### Getting data from MySQL
posts_dta <- dbGetQuery(connection, "SELECT * FROM sample_db.posts")

# checking for the columns and its content
glimpse(posts_dta)

write.csv(posts_dta, file = "POSTS_DATA.csv")


#disconnect from dbase
dbDisconnect(connection)